CREATE DATABASE ddongstagram;

CREATE TABLE Users(
	usersId BIGINT AUTO_INCREMENT PRIMARY KEY,
	nickName VARCHAR(20) NOT NULL,
	userImage VARCHAR(255),
	createAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Board(
	bno BIGINT AUTO_INCREMENT PRIMARY KEY,
	usersId BIGINT NOT NULL REFERENCES Users(UsersId) ON DELETE CASCADE,
	title VARCHAR(90) NOT NULL,
	content TEXT NOT NULL,
	createAt DATETIME default CURRENT_TIMESTAMP,
	updateAt DATETIME default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE BoardImage(
	imageId BIGINT AUTO_INCREMENT PRIMARY KEY,
	bno BIGINT NOT NULL REFERENCES Board(Bno) ON DELETE CASCADE,
	fileName VARCHAR(255) NOT NULL
);

CREATE TABLE reply(
	rno BIGINT AUTO_INCREMENT PRIMARY KEY,
	bno BIGINT NOT NULL REFERENCES Board(Bno) ON DELETE CASCADE,
	usersId BIGINT NOT NULL REFERENCES Users(usersId) ON DELETE CASCADE,
	content TEXT NOT NULL,
	createAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updateAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT * FROM users;
SELECT * FROM board;
SELECT * FROM boardimage;
SELECT * FROM reply;

DROP TABLE users;
DROP TABLE Board;
DROP TABLE boardimage;
DROP TABLE reply;

INSERT INTO users(NickName, UserImage) VALUES('DDong', 'test.png');

select * from users where UsersId = 1;